import pytest

from solution import is_part_number

TEST_CASES = [
    """
    ........
    ..123*..
    ........
    """,
    """
    ........
    .*123...
    ........
    """,
    """
    ........
    ..123...
    ...*....
    """,
    """
    ........
    ..123...
    .*......
    """,
]


@pytest.mark.parametrize("case", TEST_CASES)
def test(case):
    input = [list(line.strip()) for line in case.strip().splitlines()]
    assert is_part_number(input, 1, 2, 3)
